# Generated by Django 5.0.5 on 2024-05-07 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Licence', 'Licence'), ('Master', 'Master')], max_length=15)),
                ('duration_years', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='cycle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.cycle'),
        ),
        migrations.CreateModel(
            name='UniteEnseignement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('coefficient', models.IntegerField()),
                ('cycle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.cycle')),
            ],
        ),
    ]
