# Generated by Django 5.0.5 on 2024-05-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_cycle_course_cycle_uniteenseignement'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniteenseignement',
            name='matieres',
            field=models.ManyToManyField(related_name='unite_enseignements', to='main_app.subject'),
        ),
    ]
