# Generated by Django 5.0.5 on 2024-05-07 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_uniteenseignement_matieres'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cycle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.cycle'),
        ),
    ]
