# Generated by Django 5.0.5 on 2024-05-08 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_subject_cycle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycle',
            name='duration_years',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='cycle',
        ),
        migrations.AlterField(
            model_name='course',
            name='cycle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.cycle'),
        ),
    ]
