# Generated by Django 5.0.5 on 2024-05-08 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_cycle_duration_years_remove_subject_cycle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniteenseignement',
            name='cycle',
        ),
        migrations.AddField(
            model_name='uniteenseignement',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.course'),
        ),
    ]
