# Generated by Django 5.0.5 on 2024-05-08 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_uniteenseignement_cycle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='years',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbr', models.IntegerField()),
                ('cycle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.cycle')),
            ],
        ),
    ]
