# Generated by Django 5.0.5 on 2024-05-08 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_years_nbr'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='years',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.years'),
        ),
        migrations.AlterField(
            model_name='years',
            name='nbr',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1),
        ),
    ]
