# Generated by Django 5.0.5 on 2024-05-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_years_nbr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='years',
            name='nbr',
        ),
        migrations.AddField(
            model_name='years',
            name='name',
            field=models.CharField(choices=[('1ère Année', '1ère Année'), ('2eme Année', '2eme Année'), ('3eme Année', '3eme Année')], max_length=15, null=True),
        ),
    ]
