# Generated by Django 5.0.5 on 2024-05-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_remove_years_nbr_years_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='years',
            name='name',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
