# Generated by Django 5.0.5 on 2024-05-08 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_course_years'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='years',
        ),
        migrations.AddField(
            model_name='subject',
            name='years',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.years'),
        ),
    ]
