# Generated by Django 5.0.5 on 2024-05-09 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_remove_course_years_subject_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='UE',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.uniteenseignement'),
        ),
    ]
