# Generated by Django 5.0.5 on 2024-05-09 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_studentresult_ue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentresult',
            old_name='UE',
            new_name='ue',
        ),
    ]
