# Generated by Django 5.0.5 on 2024-05-09 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_rename_ue_studentresult_ue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='ue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.uniteenseignement'),
        ),
    ]
